name: Sorting Madness CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Validate, build and run tests
        run: mvn --batch-mode --update-snapshots verify
      - name: Prepare JAR package
        run: mvn package
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sorting-madness-jar-package
          path: target/*.jar
      - name: Prepare doc
        run: mvn site
      - name: Upload doc
        uses: actions/upload-artifact@v3
        with:
          name: sorting-madness-doc
          path: target/*